- name: Create mysql group
  group: name=mysql system=yes

- name: Create mysql user
  user: name=mysql group=mysql system=yes

- name: mount /var/lib/mysql
  mount: name=/var/lib/mysql src="{{MYSQL_OPENSTACK_DB_DEVICE}}" fstype=ext4 state=mounted

- name: chown -R /var/lib/mysql
  file: path=/var/lib/mysql owner=mysql group=mysql recurse=yes state=directory

- name: chmod /var/lib/mysql
  file: path=/var/lib/mysql mode=700 state=directory

- name: copy mysql key
  copy: src=mysql.key dest=/root/mysql.sign.key

- name: add mysql key
  shell: apt-key add /root/mysql.sign.key

- name: add mysql list
  copy: src=mysql.list dest=/etc/apt/sources.list.d/mysql.list
