
- name: install deps
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ DALITE_REQUIREMENTS }}"
- name: install build deps
  apt:
    name: "{{ item }}"
    state: build-dep
    # build deps for Python like to install texlive in recommends.
    install_recommends: no
  with_items:
    - "{{ PYTHON_BUILD_DEP_REQIREMENTS }}"

- name: Create dalite user
  user:
    name: "{{ DALITE_USER_NAME }}"
    home: "{{ DALITE_USER_HOME }}"
    shell: "/bin/bash"

- name: Create log dir
  file: name={{ DALITE_LOG_DOWNLOAD_LOG_DIR }} state=directory owner={{ DALITE_USER_NAME }}

- include: deploy-app.yaml
- include: deploy-gunicorn.yaml